version: '3'
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=http://34.204.99.50:3500/api/tasks
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    depends_on:
      - backend
      - mongodb

  backend:
    build:
      context: ./backend
    container_name: backend-app
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_CONN_STR=mongodb://mongodb:27017/mydatabase
      - PORT=3500
    ports:
      - "3500:3500"
    command: bash -c "npm install && node ./index.js"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: